##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.13.0-B3] date: [Mon Jul 19 11:40:50 CST 2021] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Stm32EdgeImpulse


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32l4xx_it.c \
Core/Src/stm32l4xx_hal_msp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_qspi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c \
Core/Src/system_stm32l4xx.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_add_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_add_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/BayesFunctions/arm_gaussian_naive_bayes_predict_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_common_tables.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_common_tables_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_const_structs.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_const_structs_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_mve_tables.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables/arm_mve_tables_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_cos_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_cos_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_cos_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_sin_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_sin_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_sin_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_sqrt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_sqrt_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_vexp_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions/arm_vlog_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_linear_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_linear_predict_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_polynomial_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_polynomial_predict_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_rbf_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_rbf_predict_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_sigmoid_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions/arm_svm_sigmoid_predict_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_barycenter_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_bitonic_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_bubble_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_copy_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_copy_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_copy_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_copy_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_fill_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_fill_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_fill_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_fill_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_heap_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_insertion_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_merge_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_merge_sort_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_float.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_float.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_float.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_quick_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_selection_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_sort_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_sort_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_spline_interp_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions/arm_weighted_sum_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_init_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_init_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_f16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix8_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_dct4_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f64.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_f32.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions/arm_rfft_q31.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions/arm_nn_activations_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions/arm_relu6_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions/arm_relu_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions/arm_relu_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_add_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_w.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_x.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_y.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions/arm_concatenation_s8_z.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_HWC_q7_fast_nonsquare.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_basic.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_RGB.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_basic_nonsquare.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_HWC_q7_fast_nonsquare.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_u8_basic_ver1.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_q7_q15_reordered.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16_reordered.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_mat_q7_vec_q15_opt.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q15_opt.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_q7_opt.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions/arm_fully_connected_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_accumulate_q7_to_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_add_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mult_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_nntables.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_no_shift.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_no_shift.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_reordered_with_offset.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions/arm_avgpool_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions/arm_max_pool_s8_opt.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions/arm_pool_q7_HWC.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/ReshapeFunctions/arm_reshape_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q15.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_u8.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_with_batch_q7.c \
Middlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/edge-impulse-sdk/tensorflow/lite/c/common.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l475xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L475xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32L4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/Third_Party/EdgeImpulse_new0715_MachineLearning/edgeimpulse/


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L475VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
